name: ECPay
main: com.brian.ECPay.ECPay
version: ${full.version}
author: 0obrino0
website: www.youtube.com/user/brian041301
api-version: 1.13
depend: [SmartInvs]
commands:
   ecpay:
      description: ECPay Commands.
permissions:
   ECPay.*:
      default: op
      description: Give players with op everything by default
      children:
         ECPay.user.*: true
         ECPay.admin.*: true
   ECPay.user.*:
      default: true
      children:
         ECPay.user: true
         ECPay.user.menu: true
         ECPay.user.help: true
   ECPay.admin.*:
      default: op
      children:
         ECPay.admin: true
         ECPay.admin.test: true
         ECPay.admin.reload: true
         ECPay.admin.mysql: true
         ECPay.admin.notpay: true