name: ECPay
main: com.brian.ECPay.ECPay
version: ${full.version}
author: 0obrino0
website: www.youtube.com/user/brian041301
api-version: 1.13
depend: [SmartInvs]
commands:
   ecpay:
      description: ECPay Commands.
      permission: ECPay.player
      permission-message: you can not use it
permissions:
   ECPay.player:
      description: the base command can use.
      default: true